name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
    - uses: chrislennon/action-aws-cli@v1.1
    - run: |
        set -o xtrace
        cd "$GITHUB_WORKSPACE"
        yarn install
        yarn build

        BUILD_ID=`cat .next/BUILD_ID`
        INDEX_FILE=".next/server/static/$BUILD_ID/pages/index.html"

        echo "Deploying $BUILD_ID"
        aws s3 sync .next "s3://$AWS_BUCKET/_next" --cache-control public --acl public-read > /dev/null
        aws s3 cp $INDEX_FILE "s3://$AWS_BUCKET/index.html" --cache-control public --acl public-read
        aws cloudfront create-invalidation --distribution-id "$CLOUD_FLARE_DISTRIBUTION_ID" --paths /index.html
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-west-2'
        AWS_BUCKET: 'nasrmaswood.com'
        CLOUD_FLARE_DISTRIBUTION_ID:  ${{ secrets.CLOUD_FLARE_DISTRIBUTION_ID}}


