# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
    - uses: chrislennon/action-aws-cli@v1.1
      with:
        node-version: '12'
      run: |
        echo "Install yarn"
        cd "$GITHUB_WORKSPACE"
        yarn install
        yarn build

        BUILD_ID=`cat .next/BUILD_ID`
        INDEX_FILE=".next/server/static/$BUILD_ID/pages/index.html"

        echo "Deploying $BUILD_ID"
        aws s3 sync .next s3://nasrmaswood.com/next_ --cache-control public --acl public-read
        aws s3 cp $INDEX_FILE s3://nasrmaswood.com/index.html --cache-control public --acl public-read
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
